# Pandas

1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [1]:
# if you are executing this in terminal than don't use ! symbol 
# and here and in google colab you have to use this symbol

!pip install pandas

In [51]:
import pandas as pd
import numpy as np

In [52]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4) , index=['Row1','Row2','Row3','Row4','Row5'] , columns=['Col1', 'Col2', 'Col3', 'Col4'] )

In [55]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [56]:
df.tail()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [57]:
type(df)

pandas.core.frame.DataFrame

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int64
 1   Col2    5 non-null      int64
 2   Col3    5 non-null      int64
 3   Col4    5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [59]:
df.describe()

Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [60]:
# Indexing
# 1.columnname[[]]
# 2. rowindex[.loc]
# 3. columnindex number[.iloc]

df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [61]:
# columnname
type(df['Col1'])

pandas.core.series.Series

In [62]:
df[['Col1','Col2','Col3']]

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [63]:
# row index
df.loc[['Row3','Row4']]

Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15

In [64]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [65]:
df.iloc[2:4 ,0:2]

Col1  Col2
Row3     8     9
Row4    12    13

In [66]:
df.iloc[2:,1:]

Col2  Col3  Col4
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [67]:
# convert dataframe into arrays

df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [80]:
# Basic Operations

df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [81]:
df1= pd.DataFrame(data=[[1,np.nan,2],[1,3,4]], index=['Row1','Row2'] , columns=['Col1','Col2','Col3'])

In [82]:
df1

Col1  Col2  Col3
Row1     1   NaN     2
Row2     1   3.0     4

In [83]:
df1.isnull().sum()

Col1    0
Col2    1
Col3    0
dtype: int64

In [84]:
df1.isnull().sum()==0

Col1     True
Col2    False
Col3     True
dtype: bool

In [85]:
df1['Col3'].value_counts()

Col3
2    1
4    1
Name: count, dtype: int64

In [86]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [89]:
df['Col2'].unique()

array([ 1,  5,  9, 13, 17])

In [90]:
df[df['Col2']>2]

Col1  Col2  Col3  Col4
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19