# Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [99]:
# import the library

import numpy as np

lst=[1,2,3,4]
arr=np.array(lst)

In [100]:
type(arr)

numpy.ndarray

In [101]:
arr.shape

(4,)

In [102]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [103]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [104]:
arr1.shape

(3, 5)

In [105]:
arr

array([1, 2, 3, 4])

In [106]:
# indexing

arr[3]

4

In [107]:
arr[3]=5

In [108]:
arr

array([1, 2, 3, 5])

In [109]:
arr[-1]

5

In [110]:
arr[::]

array([1, 2, 3, 5])

In [111]:
arr[:-1]

array([1, 2, 3])

In [112]:
arr[::-2]

array([5, 2])

In [113]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [114]:
arr1[:,3:].shape

(3, 2)

In [115]:
arr1[:,1]

array([2, 3, 4])

In [116]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [117]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [118]:
arr1[:, [0, -1]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [119]:
# EDA
arr

array([1, 2, 3, 5])

In [120]:
arr[arr<2]

array([1])

In [121]:
arr *arr

array([ 1,  4,  9, 25])

In [122]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [123]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [124]:
# mechanism to create an array

np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [125]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [126]:
arr1 * arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [127]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [128]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [129]:
np.random.randint(10,50,4).reshape(2,2)

array([[47, 16],
       [48, 40]])

In [137]:
# randn → It generates numbers from a normal distribution (mean = 0, std = 1)
# the values can be negative, positive, or even zero.

np.random.randn(3,5)

array([[ 0.17645891,  0.70851922, -0.90012794,  1.2031093 , -1.98938791],
       [-0.07804479, -1.1942921 , -2.0648304 ,  0.33501368, -0.4153872 ],
       [ 2.60163914,  1.17909065, -1.51611209, -0.62778146,  1.98409158]])

In [139]:
# random_sample → It generates numbers from a uniform distribution in the range [0, 1)
# so the values are always positive but less than 1.

np.random.random_sample((3,5))

array([[0.52749633, 0.55364464, 0.88119686, 0.87977673, 0.41699251],
       [0.29598759, 0.99532236, 0.01074242, 0.34530725, 0.33266582],
       [0.47382338, 0.71349668, 0.09886506, 0.41065695, 0.87458643]])